-- vim: filetype=SQL
CREATE TABLE settings (
	key   TEXT PRIMARY KEY,
	value TEXT NOT NULL,

	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
